# Generated by Django 5.0.4 on 2024-04-26 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('description', models.CharField(blank=True, max_length=1500)),
                ('buyingPrice', models.IntegerField(blank=True, default=0, verbose_name='buyingPrice')),
                ('sellingPrice', models.IntegerField(blank=True, default=0, verbose_name='sellingPrice')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('carImg', models.ImageField(upload_to='images/')),
                ('ownerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
