# Generated by Django 4.1.5 on 2023-10-31 16:43

from django.db import migrations, models
import enums.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Succulent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('succulent_type', models.CharField(blank=True, max_length=150)),
                ('importedFrom', models.IntegerField(choices=[(0, 'BANGLADESH'), (1, 'INDIA'), (2, 'THILAND'), (3, 'CHINA'), (4, 'VIETNAM'), (5, 'PHILIPINES')], default=enums.models.CountryTypes['BANGLADESH'])),
                ('buyingPrice', models.IntegerField(blank=True, verbose_name='buyingPrice')),
                ('sellingPrice', models.IntegerField(blank=True, verbose_name='sellingPrice')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
