# Generated by Django 5.0.4 on 2024-04-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('succulents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='succulent',
            name='buyingPrice',
            field=models.IntegerField(blank=True, default=0, verbose_name='buyingPrice'),
        ),
        migrations.AlterField(
            model_name='succulent',
            name='sellingPrice',
            field=models.IntegerField(blank=True, default=0, verbose_name='sellingPrice'),
        ),
    ]
